#
# A Makefile for COMP
# (c) osFree project,
# author, date
#

PROJ      = comp
TRGT      = $(PROJ).com
DESC      = Binary comparison of files
#defines object file names in format $(p)objname$(e)
srcfiles  = $(p)comp$(e)
# subject to change to dual mode application
COM = 1
NOLIBS = 1

!include $(%ROOT)tools/mk/appsdos.mk

