#
# Makefile for DOS Commands Shared Library
#

PROJ      = doscmd_shared
ADD_COPT  = -ml -i=$(MYDIR)..$(SEP)include
SOURCES   = tcc2wat kitten prf
DIRS      = dflatp
TARGET_API = DOS
TARGET_CLASS = LIBRARY

!include $(%ROOT)tools/mk/build.mk
