#
# A Makefile for APPEND
# (c) osFree project,
# author, date
#

PROJ      = assign
TRGT      = $(PROJ).com
DESC      = Binary comparison of files
srcfiles  = $(p)asgn_tsr$(e)
COM       = 1
NOLIBS    = 1

!include $(%ROOT)tools/mk/appsdos.mk

.asm: $(BASE)..
