# DOS/CMD/assign/tsr/makefile
#
# A Makefile for ATTRIB
# (c) osFree project,
# author, date
#

PROJ = asgn_tsr
DESC = Assign TSR part
SOURCES = asgn_tsr
COM = 1
NOLIBS = 1

!include $(%ROOT)tools/mk/build.mk



