#
# A Makefile for ATTRIB
# (c) osFree project,
# author, date
#

PROJ = asgn_tsr
DESC = Assign TSR part
srcfiles = $(p)asgn_tsr$(e)
COM = 1
NOLIBS = 1
TARGET_API = DOS

!include $(%ROOT)tools/mk/build.mk



