#
# A Makefile for EXIT_VDM
# (c) osFree project,
# author, date
#

DESC       = Exit VDM
TARGET_API = DOS
COM        = 1

ADD_COPT  = -i=$(MYDIR)..$(SEP)..$(SEP)include
ADD_LINKOPT = lib $(BLD)lib$(SEP)dos_shared.lib

!include $(%ROOT)tools/mk/build.mk
