#
# A Makefile for EXIT_VDM
# (c) osFree project,
# author, date
#

PROJ      = exit_vdm
TRGT      = $(PROJ).com
DESC      = Exit VDM
srcfiles  = $(p)exit_vdm$(e)
COM =1

ADD_COPT  = -i=$(MYDIR)..$(SEP)..$(SEP)include
ADD_LINKOPT = lib $(BLD)lib$(SEP)dos_shared.lib

!include $(%ROOT)tools/mk/appsdos.mk
