#
# A Makefile for SUBST
# (c) osFree project,
# author, date
#

DESC = Substitute path to drive letter
# defines additional options for C compiler
ADD_COPT=-i=$(MYDIR)..$(SEP)..$(SEP)include
ADD_LINKOPT = lib dos_shared.lib libpath $(ROOT)build$(SEP)lib
TARGET_API = DOS

!include $(%ROOT)tools/mk/build.mk
