#
# A Makefile for XCOPY
# (c) osFree project,
# author, date
#

DESC = Extended COPY tool
#defines object file names in format $(p)objname$(e)
SOURCES = xcopy kitten prf
# defines additional options for C compiler
TARGET_API = DOS

!include $(%ROOT)tools/mk/build.mk
!include $(MYDIR)xcopy.mk

.c: $(PORT_BASE)source

.h: $(PORT_BASE)source
