#
# A Makefile for FC
# (c) osFree project,
# author, date
#

DESC = Ask for user input
#defines object file names in format $(p)objname$(e)
SOURCES = choice kitten
# defines additional options for C compiler
TARGET_API = DOS

!include $(%ROOT)tools/mk/build.mk
!include $(MYDIR)choice.mk

.c: $(PORT_BASE)source$(SEP)choice

.h: $(PORT_BASE)source$(SEP)choice
