#
# A main Makefile for osFree Command Line tools project
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS =   shared    &
         attrib    &
         help      &
         find      &
         diskcomp  &
         label     &
         mem       &
         xcopy     &
         basic     &
         more      &
         subst     &
         stub      &
         command   &
         debug     &
         comp      &
         append    &
         exit_vdm  &
         edlin

!include $(%ROOT)/mk/all.mk

