#
# A main Makefile for osFree Command Line tools project
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS =   shared    &
         append    &
         attrib    &
         basic     &
         command   &
         comp      &
         debug     &
         diskcomp  &
         edlin     &
         exit_vdm  &
         find      &
         help      &
         label     &
         mem       &
         more      &
         move      &
         sort      &
         stub      &
         subst     &
         xcopy

!include $(%ROOT)tools/mk/all.mk
