#
# A main Makefile for osFree Command Line tools project
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS =   shared    &
         stub      &
         append    &
         assign    &
         attrib    &
         basic     &
         choice    &
         command   &
         comp      &
         debug     &
         diskcomp  &
		 diskcopy  &
         edlin     &
         exit_vdm  &
         find      &
		 graftabl  &
         help      &
         join      &
         label     &
         mem       &
         more      &
         move      &
         qbasic    &
         sort      &
         xcopy	&
	expand	&
	fastopen
#         subst     &
#         lxloader  &

!include $(%ROOT)tools/mk/all.mk
