#
# A Makefile for JOIN
# (c) osFree project,
# author, date
#

DESC = join drive to subdirectory
# defines additional options for C compiler
ADD_COPT=-i=$(MYDIR)..$(SEP)..$(SEP)include
ADD_LINKOPT = lib dos_shared.lib libpath $(ROOT)build$(SEP)lib
TARGET_API = DOS

!include $(%ROOT)tools/mk/build.mk
