# $Id: makefile,v 1.3 2004/08/21 14:49:03 prokushev Exp $
#
# Makefile for Watcom/LIBC interface layer

PROJ      = dos_shared
ADD_COPT  = -i=$(MYDIR)..$(SEP)include
TARGET_API  = DOS
TARGET_CLASS  = LIBRARY

!include $(%ROOT)tools/mk/build.mk
