#
# A Makefile for STUB
# (c) osFree project,
# author, date
#

PROJ = os2stub
DESC = DOS Stub for OS/2 executables
ADD_COPT=-i=$(MYDIR)..$(SEP)..$(SEP)include
ADD_LINKOPT = lib dos_shared.lib libpath $(ROOT)build$(SEP)lib
TARGET_API = DOS

DEST = os2$(SEP)mdos

!include $(%ROOT)tools/mk/build.mk
