#
# A Makefile for ATTRIB
# (c) osFree project,
# author, date
#

PROJ = bin2c
TRGT = $(PROJ).exe
DESC = bin to c converter
srcfiles = $(p)bin2c$(e)

!include $(%ROOT)tools/mk/tools.mk
#!include $(MYDIR)..$(SEP)port$(SEP)assign.mk

#.asm: $(PORT_BASE)SOURCE$(SEP)ASSIGN


